name: languagex
description: Definex Languagex Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+29

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

  provider: 6.0.5
  path_provider: ^2.0.14
  dart_json_mapper: 2.2.7+1
  property_change_notifier: 0.3.0

  intl: 0.17.0
  hive_flutter: 1.1.0

  retrofit: 4.0.1
  logger: any
  dio: ^5.1.1
  dio_http2_adapter:
  jwt_decode: 0.3.1

  auto_route: 5.0.4
  reflectable: ^4.0.5
  flutter_flavor: ^3.1.1
  platform_device_id: ^1.0.1
  printing: ^5.10.3

  permission_handler: 10.2.0
  device_info_plus: ^8.2.2
  package_info_plus: ^3.1.2
  image_picker: ^0.8.7+4
  file_picker: ^5.2.11
  mime: 1.0.4
  syncfusion_flutter_pdfviewer: ^21.1.41
  photo_view: 0.14.0
  flutter_datetime_picker: 1.5.1

  fluttertoast: ^8.2.1
  adaptive_dialog: ^1.8.3
  flutter_svg: ^2.0.5
  cached_network_image: 3.2.3
  animate_do: 3.0.2
  avatar_glow: 2.0.2
  google_ml_kit: ^0.15.0


  #  firebase_core: ^2.5.0
#  firebase_analytics: ^10.1.1
#  firebase_crashlytics: ^3.0.12
#  firebase_messaging: ^14.2.2
#  flutter_local_notifications: ^14.0.0
#  firebase_remote_config: ^4.0.1
  launch_review: ^3.0.1
#  open_mail_app: ^0.4.5
#  pinput: ^2.2.31
#  syncfusion_flutter_charts: ^21.1.41
#  syncfusion_flutter_datagrid: ^21.1.41
#  charts_flutter: ^0.12.0

  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3

dev_dependencies:
  build_runner: 2.3.3
  auto_route_generator: 5.0.3
  flutter_lints: 2.0.1

  retrofit_generator:
    path: retrofit_generator/


flutter:

    uses-material-design: true

    assets:
      - assets/
      - assets/images/
      - assets/svg/
      - assets/svg/bottombar/
      - assets/fonts/
      - assets/translations/

    fonts:
      - family: interBlack
        fonts:
          - asset: assets/fonts/Inter-Black.ttf

      - family: interBold
        fonts:
          - asset: assets/fonts/Inter-Bold.ttf

      - family: interExtraBold
        fonts:
          - asset: assets/fonts/Inter-ExtraBold.ttf

      - family: interExtraLight
        fonts:
          - asset: assets/fonts/Inter-ExtraLight.ttf

      - family: interLight
        fonts:
          - asset: assets/fonts/Inter-Light.ttf

      - family: interMedium
        fonts:
          - asset: assets/fonts/Inter-Medium.ttf

      - family: interRegular
        fonts:
          - asset: assets/fonts/Inter-Regular.ttf

      - family: interSemiBold
        fonts:
          - asset: assets/fonts/Inter-SemiBold.ttf

      - family: interThin
        fonts:
          - asset: assets/fonts/Inter-Thin.ttf
